-- public.tbl_setting_uw definition

-- Drop table

-- DROP TABLE public.tbl_setting_uw;

CREATE TABLE public.tbl_setting_uw (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	insured_name bool NULL,
	policy_no bool NULL,
	certificate_no bool NULL,
	inception_date bool NULL,
	sum_insured bool NULL,
	stnc bool NULL,
	days_180_more bool NULL,
	pl_cedant_rate bool NULL,
	pl_tre bool NULL,
	claim_paid_by_cedant_100 bool NULL,
	claim_paid_tre_share_calc_by_cedant bool NULL,
	claim_paid_tre_share_calc_by_tre bool NULL,
	check_claim_tre_share bool NULL,
	over_all_claim_stts bool NULL,
	remark bool NULL,
	ceding_name varchar NULL,
	treaty_name varchar NULL,
	create_date timestamp NULL DEFAULT now(),
	days_180_less bool NULL
);